- hosts: 192.168.0.160
  tasks:
    - name: install roles
      shell: |
        ansible-galaxy install geerlingguy.mysql 
        ansible-galaxy install PowerDNS.pdns
        ansible-galaxy install PowerDNS.pdns_recursor
- hosts: 192.168.0.160
  become: yes
  vars_files:
    - vars/my_main.yml
  roles:
    - role: geerlingguy.mysql      
      
- hosts: 192.168.0.160
  roles:
    - { role: PowerDNS.pdns }
  vars:
    pdns_config:
      master: true
      slave: false
      local-port: 5300
      local-address: '192.168.0.160'
    pdns_backends:
      gmysql:
        host: localhost
        port: 3306
        user: powerdns
        password: powerdns
        dbname: pdns
    pdns_backends_mysql_credential:
      gmysql:
        priv_user: root
        priv_password: 123456
        priv_host:
          - "localhost"
    pdns_install_repo: "{{ pdns_auth_powerdns_repo_41 }}"

- hosts: 192.168.0.160
  roles:
    - { role: PowerDNS.pdns_recursor }
  vars:
    pdns_rec_config:
      'allow-from':
        - '198.168.0.0/24'
        - '10.0.0.0/8'
      'local-address': '192.168.0.160:53'    
    pdns_rec_install_repo: "{{ pdns_rec_powerdns_repo_41 }}"
